XELTX = C:\texlive\2015\bin\win32\xelatex.exe -synctex=1 -interaction=nonstopmode --src-specials
MKINDX = C:\texlive\2015\bin\win32\makeindex.exe

all :
	$(XELTX) HexagonBook.tex
	$(MKINDX) HexagonBook.idx
	$(XELTX) HexagonBook.tex