
all :
	xelatex -synctex=1 -interaction=nonstopmode --src-specials HexagonBook.tex
	makeindex HexagonBook.idx
	xelatex -synctex=1 -interaction=nonstopmode --src-specials HexagonBook.tex
	xelatex -synctex=1 -interaction=nonstopmode --src-specials HexagonBook.tex